
var com=com||{};com.unitedCoders=com.unitedCoders||{};com.unitedCoders.geo=com.unitedCoders.geo||{};com.unitedCoders.geo.ll=com.unitedCoders.geo.ll||[];var geo=com.unitedCoders.geo;com.unitedCoders.geo.staticMapUrl=function(x,y){var url="//maps.google.com/maps/api/staticmap?sensor=false&size="+x+"x"+y+"&markers=";var colors=["blue","green","red","yellow","white","black"];var m=[];for(var i=0;i<this.ll.length;i++){var s=this.ll[i];m.push("size:mid|color:"+colors[i]+"|label:"+(i+1)+"|"+s.lat+","+s.long);};m.push("color:black|label:0|"+this.getLat()+","+this.getLong())
return url+m.join("&markers=")};if(window['google']&&google.loader&&google.loader.ClientLocation){com.unitedCoders.geo.ll.push({'name':'google','country':google.loader.ClientLocation.country||'','city':google.loader.ClientLocation.city||'','long':google.loader.ClientLocation.longitude,'lat':google.loader.ClientLocation.latitude});};com.unitedCoders.geo.getLat=function(){if(!this.lat){this.calcLL();}
return this.lat;};com.unitedCoders.geo.getLong=function(){if(!this.long){this.calcLL();}
return this.long;};com.unitedCoders.geo.calcLL=function(){var lat=0.0,long=0.0,count=0,latVar=0,lonVar=0;this.acuracy=0;for(var i=0;i<this.ll.length;i++){var node=this.ll[i];if(node.long&&node.lat){lat+=parseFloat(node.lat)*(1+!!node.city);long+=parseFloat(node.long)*(1+!!node.city);count+=1+(!!node.city);}}
if(count){this.lat=lat/count;this.long=long/count;}
count=0;for(var i=0;i<this.ll.length;i++){var node=this.ll[i];if(node.long&&node.lat){latVar+=Math.abs(this.lat-node.lat);lonVar+=Math.abs(this.long-node.long);count+=1;}}
this.acuracy=this.distanceFromUser(latVar,lonVar)*1000;};com.unitedCoders.geo.getPosition=function(){return{lat:this.getLat(),long:this.getLong()};};com.unitedCoders.geo.getLocation=function(){var ret=this.ll[0];for(var i=0;i<this.ll.length;i++){var pos=this.ll[i];var minDist=10000;if(pos['city']&&pos['country']){var dist=this.distanceFromUser(this.getLat(),this.getLong());if(minDist>dist){minDist=dist;ret=pos;}}}
return ret;};com.unitedCoders.geo.cityFound=function(cities){for(var i=0;i<cities.length;i++){for(var j=0;j<this.ll.length;j++){if(cities[i].toLowerCase()==this.ll[j].city.toLowerCase()){return true;}}}
return false;};com.unitedCoders.geo.countryFound=function(countries){for(var i=0;i<countries.length;i++){for(var j=0;j<this.ll.length;j++){if(countries[i].toLowerCase()==this.ll[j].country.toLowerCase()){return true;}}}
return false;};com.unitedCoders.geo.distanceFromUser=function(lat1,lon1){var lat2=this.getLat();var lon2=this.getLong();return 6378.7*Math.acos(Math.sin(lat1/57.2958)*Math.sin(lat2/57.2958)+Math.cos(lat1/57.2958)*Math.cos(lat2/57.2958)*Math.cos(lon2/57.2958-lon1/57.2958))
var dLat=(lat2-lat1).toRad();var dLon=(lon2-lon1).toRad();var a=Math.sin(dLat/2)*Math.sin(dLat/2)+
Math.cos(lat1.toRad())*Math.cos(lat2.toRad())*Math.sin(dLon/2)*Math.sin(dLon/2);var c=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));return d=6371*c;};com.unitedCoders.geo.differenceFromUser=com.unitedCoders.geo.distanceFromUser;com.unitedCoders.geo.generate_map=function(x,y,param){var html="";var url=this.staticMapUrl(x,y);if(param){url+="&"+paramStr;}
var li="";for(var i=0;i<this.ll.length;i++){var s=this.ll[i];if(s.lat&&s.long){li+="<li>"+s.name+": "+s.city+", "+s.country+" </li>";}};html+="<div id='local_map'><img sr"+"c='"+url+"'><ol>"+li+"</ol></div>";return html;};com.unitedCoders.geo.getCurrentPosition=function(success,error,params){var self=this;var timeId=setTimeout(function(){clearTimeout(timeId);success({coords:{latitude:self.getLat(),longitude:self.getLong(),accuracy:self.accuracy},timestamp:new Date()});},1);if(navigator&&navigator.geolocation&&enableHighAccuracy in params)
navigator.geolocation.getCurrentPosition(success,error,params);};com.unitedCoders.geo.watchPosition=function(success,error,params){return 1;};com.unitedCoders.geo.clearWatch=function(watchId){};